# Generated by Django 3.0.8 on 2020-07-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_gif',
            field=models.FileField(blank=True, null=True, upload_to='uploads/gifs/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video_file',
            field=models.FileField(upload_to='uploads/videos/'),
        ),
    ]
