# Generated by Django 3.0.8 on 2020-07-25 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200725_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='share_pointer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='posts.Post'),
        ),
    ]
