# Generated by Django 3.0.8 on 2020-09-15 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0006_auto_20200915_1835'),
        ('posts', '0005_post_is_pornographic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sounds.Sound'),
        ),
    ]
