# Generated by Django 3.0.8 on 2020-09-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20200923_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_downloadable',
            field=models.BooleanField(default=False),
        ),
    ]
