# Generated by Django 3.0.8 on 2020-08-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='reason',
            field=models.IntegerField(choices=[(0, 'Account Activation'), (1, 'Celebrity Verification'), (2, 'Password Reset'), (3, 'Unusual Activity'), (4, 'Other')], default=4, null=True),
        ),
    ]
