# Generated by Django 3.0.8 on 2020-09-30 16:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '__first__'),
        ('usermodule', '__first__'),
        ('sounds', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('comment', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermodule.Profile')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_link', to='activity.Comment')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SoundView',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermodule.Profile')),
                ('sound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sounds.Sound')),
            ],
            options={
                'unique_together': {('profile', 'sound')},
            },
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermodule.Profile')),
            ],
            options={
                'unique_together': {('profile', 'post')},
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Comment')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermodule.Profile')),
            ],
            options={
                'unique_together': {('profile', 'comment')},
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('activity_type', models.CharField(choices=[('F', 'Favorite'), ('L', 'Like'), ('R', 'Report')], max_length=1)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermodule.Profile')),
            ],
            options={
                'unique_together': {('profile', 'post', 'activity_type')},
            },
        ),
    ]
