# Generated by Django 3.0.8 on 2020-09-05 14:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0004_auto_20200806_1324'),
        ('activity', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activity.Comment')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usermodule.Profile')),
            ],
            options={
                'unique_together': {('profile', 'comment')},
            },
        ),
    ]
