# Generated by Django 3.0.8 on 2020-09-05 15:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0004_auto_20200806_1324'),
        ('posts', '0005_post_is_pornographic'),
        ('sounds', '0005_sound_sound_cover'),
        ('activity', '0003_commentlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundView',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usermodule.Profile')),
                ('sound', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sounds.Sound')),
            ],
            options={
                'unique_together': {('profile', 'sound')},
            },
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posts.Post')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usermodule.Profile')),
            ],
            options={
                'unique_together': {('profile', 'post')},
            },
        ),
    ]
