# Generated by Django 3.0.8 on 2020-09-23 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20200923_0400'),
        ('usermodule', '0004_auto_20200806_1324'),
        ('sounds', '0007_auto_20200923_0400'),
        ('activity', '0004_postview_soundview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_link', to='activity.Comment'),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Comment'),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermodule.Profile'),
        ),
        migrations.AlterField(
            model_name='postview',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
        migrations.AlterField(
            model_name='postview',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermodule.Profile'),
        ),
        migrations.AlterField(
            model_name='soundview',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermodule.Profile'),
        ),
        migrations.AlterField(
            model_name='soundview',
            name='sound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sounds.Sound'),
        ),
    ]
