# Generated by Django 3.0.8 on 2020-08-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0004_auto_20200817_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='sound',
            name='sound_cover',
            field=models.FileField(blank=True, null=True, upload_to='uploads/cover/'),
        ),
    ]
