# Generated by Django 3.0.8 on 2020-09-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0005_sound_sound_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='sound',
            name='is_extracted_audio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sound',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
