# Generated by Django 3.0.8 on 2020-10-01 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockeduser',
            options={'ordering': ('-created_at',), 'verbose_name': 'Blocked user', 'verbose_name_plural': 'Blocked users'},
        ),
        migrations.RemoveField(
            model_name='blockeduser',
            name='date',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='last_exit',
        ),
    ]
